Repository deepin-community/network-manager, pull requests merged in 2024-07, with the labels that each got.

#9 fix: disable broken ut
  debian/changelog
  debian/patches/0001-disable-broken-ut.patch
  debian/patches/series
Labels: approved

#12 chore: update patches
  debian/changelog
  debian/patches/0001-disable-broken-ut.patch
Labels: do-not-merge/hold

#13 chore: 增加ActivateConnection2接口
  debian/changelog
  debian/patches/series
  debian/patches/uniontech002_add_activeconnection_flags.patch
Labels: do-not-merge/hold, ok-to-test
